class PUBSUB_KEYS:
    EVENT_BAR = "EVENT-BAR"
    EVENT_BAR_CANDIDATE = ["EVENT-BAR-CANDIDATE"]
    EVENT_BAR_SAVE = ["EVENT-BAR-SAVE"]
    EVENT_BAR_FILTER_VSA = ["EVENT-BAR-CANDIDATE-CHECK"]
    EVENT_BAR_POST_TO_SERVER = ["EVENT-BAR-TRADE-ADD"]
    EVENT_BAR_STACK_ADD = ["EVENT-BAR-STACK-ADD"]
    EVENT_TRADE = "EVENT-TRADE"
    EVENT_TRADE_ADD = ["EVENT-TRADE-ADD"]
    EVENT_TRADE_NEW = ["EVENT-TRADE-NEW"]
    EVENT_TRADE_SAVE = ["EVENT-TRADE-SAVE"]
    EVENT_TRADE_PROCESS = ["EVENT-TRADE-PROCESS"]
    EVENT_TRADE_SCORE = ["EVENT-TRADE-SCORE"]
    EVENT_TRADE_SUBSCRIBE = ["EVENT-TRADE-SUBSCRIBE"]
    EVENT_BAR_CANDIDATE_HISTORICAL = ["EVENT-BAR-CANDIDATE-HISTORICAL"]
    EVENT_BAR_NEWS_ADD = ["EVENT-BAR-NEWS-ADD"]
